<?php

/**
 * sm()
 * helper function
 */

function sm($variable){
  if(is_array($variable) || is_object($variable)){
    drupal_set_message("<pre>" . print_r($variable,1) . "</pre>");
  }
  else{
    drupal_set_message($variable);
  } 
}

/**
 * hook_form_alter(&$form, &$form_state, $form_id)
 */
 
function studio_job_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "job_node_form"){
    $form['field_remaining_amount']['#attribute']['disabled'] = TRUE;
    if((arg(0) == "node") && (arg(1) == "add") && (arg(2) == "job")){
      $form['field_image_ready']['#access'] = FALSE;
      $form['field_date_ready']['#access'] = FALSE;
    }
    
  }
}

/**
 *  hook_init()
 */

function studio_job_init(){
  drupal_add_js(drupal_get_path('module', 'studio_job') . '/js/studio_job.js');
}

/**
 *
 */
 
 
 function studio_job_node_view($node, $view_mode, $langcode) {
   //sm($node->field_image_taken['und'][0]);
   //$node->field_image_taken['und'][0]['title'] = "here";
 }